spring.application.name=${Program name}
server.port=${Program's port}
spring.datasource.url=${JDBC url}
spring.datasource.username=${Database username}
spring.datasource.password=${Database password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${JWT secret}
jwt.expiration=${JWT expiration time}
supabase.url=${Supabase project's url}
supabase.anon.api=${Supabase anon api key}