do $$ begin
  begin alter table public.jobs alter column id set generated by default; exception when others then null; end;
  begin alter table public.applications alter column id set generated by default; exception when others then null; end;
end $$;
notify pgrst, 'reload schema';
