-- Post quota transaction + terms/consents
create table if not exists public.terms_versions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('terms','privacy','candidate_consent','company_policy','refund_policy','marketing')),
  version text not null,
  title text not null,
  content_url text,
  is_required boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(type, version)
);

create table if not exists public.user_consents (
  id bigint generated by default as identity primary key,
  user_email text not null,
  user_role text not null check (user_role in ('user','company','admin')),
  consent_type text not null,
  version text not null,
  ip text,
  user_agent text,
  accepted_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique(user_email, consent_type, version)
);

insert into public.terms_versions(type, version, title, content_url, is_required) values
('terms','2026-06-14','Điều khoản sử dụng','/terms.html',true),
('privacy','2026-06-14','Chính sách bảo mật','/privacy.html',true),
('candidate_consent','2026-06-14','Đồng ý xử lý CV ứng viên','/candidate-consent.html',true),
('company_policy','2026-06-14','Chính sách doanh nghiệp','/company-policy.html',true),
('refund_policy','2026-06-14','Chính sách hoàn tiền','/refund-policy.html',true),
('marketing','2026-06-14','Đồng ý nhận thông tin marketing',null,false)
on conflict(type, version) do nothing;

alter table public.company_subscriptions add column if not exists posts_limit integer;
update public.company_subscriptions set posts_limit = coalesce(posts_limit, post_limit, 0) where posts_limit is null;

create or replace function public.reserve_company_job_slot(p_company_id bigint, p_actor_email text)
returns public.company_subscriptions
language plpgsql security definer set search_path=public as $$
declare v_sub public.company_subscriptions%rowtype;
begin
  select * into v_sub
  from public.company_subscriptions
  where "companyId" = p_company_id
    and status = 'active'
    and (ends_at is null or ends_at >= now())
    and coalesce(posts_used,0) < coalesce(posts_limit, post_limit, 0)
  order by ends_at asc nulls last, id asc
  limit 1
  for update;

  if not found then
    raise exception 'Không còn gói đăng tuyển hợp lệ hoặc đã hết lượt đăng tin.';
  end if;

  update public.company_subscriptions
  set posts_used = coalesce(posts_used,0) + 1, updated_at = now()
  where id = v_sub.id
  returning * into v_sub;

  insert into public.audit_logs("actorEmail","actorRole",action,"entityType","entityId",metadata)
  values(p_actor_email,'company','reserve_job_slot','company_subscription',v_sub.id::text,jsonb_build_object('companyId',p_company_id,'postsUsed',v_sub.posts_used,'postsLimit',coalesce(v_sub.posts_limit,v_sub.post_limit)));

  return v_sub;
end $$;

create or replace function public.release_company_job_slot(p_subscription_id bigint, p_actor_email text)
returns public.company_subscriptions
language plpgsql security definer set search_path=public as $$
declare v_sub public.company_subscriptions%rowtype;
begin
  select * into v_sub from public.company_subscriptions where id = p_subscription_id for update;
  if not found then raise exception 'Không tìm thấy subscription.'; end if;
  update public.company_subscriptions
  set posts_used = greatest(0, coalesce(posts_used,0)-1), updated_at = now()
  where id = p_subscription_id returning * into v_sub;
  insert into public.audit_logs("actorEmail","actorRole",action,"entityType","entityId",metadata)
  values(p_actor_email,'system','release_job_slot','company_subscription',v_sub.id::text,jsonb_build_object('postsUsed',v_sub.posts_used));
  return v_sub;
end $$;

alter table public.jobs add column if not exists subscription_id bigint;

-- service role access for new terms tables
do $$ begin
  alter table public.terms_versions enable row level security;
  alter table public.user_consents enable row level security;
  drop policy if exists service_role_all on public.terms_versions;
  drop policy if exists service_role_all on public.user_consents;
  create policy service_role_all on public.terms_versions for all using (auth.role()='service_role') with check (auth.role()='service_role');
  create policy service_role_all on public.user_consents for all using (auth.role()='service_role') with check (auth.role()='service_role');
end $$;
notify pgrst, 'reload schema';
