alter table public.cvs add column if not exists email text;
alter table public.cvs add column if not exists name text;
alter table public.cvs add column if not exists type text;
alter table public.cvs add column if not exists ext text;
alter table public.cvs add column if not exists size bigint;
alter table public.cvs add column if not exists "uploadedAt" text;
alter table public.cvs add column if not exists industries jsonb not null default '[]'::jsonb;
do $$ begin begin alter table public.cvs alter column id set generated by default; exception when others then null; end; end $$;
notify pgrst, 'reload schema';
